name: job_env
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - sqlite
  - pip:
      - sqlalchemy
      - pydantic
      - pydantic-settings
      - httpx==0.28.1
      - beautifulsoup4==4.15.0
      - lxml
      - python-dotenv
      - pytest