[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "jobomation"
dynamic = ["version"]
description = "Local-first job discovery, scraping, and application management tool"
readme = "README.md"
license = "MIT"
authors = [{ name = "Kiran Brahmatewari", email = "lynkos@admin.com" }]
keywords = [
    "jobs",
    "job",
    "job-search",
    "scraping",
    "automation",
    "python",
    "work"
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4==4.15.0",
    "httpx==0.28.1",
    "dash==4.4.1",
    "dash-ag-grid==35.3.0"
]

[project.urls]
Homepage = "https://github.com/lynkos/jobomation"
Repository = "https://github.com/lynkos/jobomation.git"
Issues = "https://github.com/lynkos/jobomation/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/jobomation"]

[tool.hatch.version]
path = "src/jobomation/__init__.py"