companies:
  - name: DoorDash
    source_type: greenhouse
    board_id: doordashusa

  - name: Twitch
    source_type: greenhouse
    board_id: twitch

  - name: Ramp
    source_type: ashby
    board_id: ramp