targets:
  - name: DoorDash
    source: greenhouse
    args:
      board: doordashusa

  - name: Twitch
    source: greenhouse
    args:
      board: twitch

  - name: Ramp
    source: ashby
    args:
      board: ramp

  - name: Indeed - Software Engineer
    source: indeed
    args:
      search_term: software engineer
      location: United States
      results_wanted: 100

  - name: Indeed - Infrastructure
    source: indeed
    args:
      search_term: infrastructure engineer
      location: United States
      results_wanted: 100

  # - name: LinkedIn - Platform
  #   source: linkedin
  #   args:
  #     search_term: platform engineer
  #     location: United States

  # - name: Some Lever Company
  #   source: lever
  #   args:
  #     board: some-company